apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnplaterec-backend
  labels:
    app: vnplaterec-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vnplaterec-backend
  template:
    metadata:
      labels:
        app: vnplaterec-backend
    spec:
      containers:
      - name: vnplaterec-backend
        image: cnmeow/vnplaterec_backend:latest
        ports:
        - containerPort: 2106